version: '3'
services:
      myapp:
         build: ./myapp
         restart: always
         container_name: myapp
         ports:
            - 3000:3000
         volumes:
            - ./myapp:/app         
